[workspace]
members = [
    "apps/desktop/src-tauri",
    "crates/agents",
    "crates/core",
    "crates/git",
    "crates/session",
    "crates/daemon",
    "crates/storage",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.0-beta.1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
