use serde::{Deserialize, Serialize};

use crate::{ApiError, RequestId};

/// Current stable IPC protocol version.
pub const PROTOCOL_V1: u16 = 1;

/// Semantic version of the CLI Master application and `cli-masterd`.
///
/// This value matches `[workspace.package].version` in `Cargo.toml`. The
/// desktop `package.json`, Tauri config, and `protocol/catalog.json` mirrors
/// are checked against it in tests. It is not the IPC protocol version.
pub const APPLICATION_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Discriminator identifying the shape and direction of an IPC envelope.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum EnvelopeKind {
    /// A client request sent to the daemon.
    Request,
    /// A daemon response correlated with a request.
    Response,
    /// An asynchronous daemon event.
    Event,
}

/// Versioned request sent by a client to the local daemon.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct RequestEnvelope<T> {
    /// Stable envelope discriminator. Constructors always set this to `request`.
    pub kind: EnvelopeKind,
    /// Wire protocol version. This must be [`PROTOCOL_V1`].
    pub version: u16,
    /// Correlation identifier generated by the caller.
    pub request_id: RequestId,
    /// Stable dotted request name, such as `session.create`.
    pub method: String,
    /// Request-specific body.
    pub payload: T,
}

impl<T> RequestEnvelope<T> {
    /// Wraps a named request body using protocol version 1 and a new `UUIDv7`
    /// request ID.
    #[must_use]
    pub fn v1(method: impl Into<String>, payload: T) -> Self {
        Self {
            kind: EnvelopeKind::Request,
            version: PROTOCOL_V1,
            request_id: RequestId::new(),
            method: method.into(),
            payload,
        }
    }

    /// Returns whether this envelope uses the supported protocol version.
    #[must_use]
    pub const fn is_supported(&self) -> bool {
        self.version == PROTOCOL_V1 && matches!(self.kind, EnvelopeKind::Request)
    }
}

/// Versioned response correlated with an IPC request.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ResponseEnvelope<T> {
    /// Stable envelope discriminator. Constructors always set this to `response`.
    pub kind: EnvelopeKind,
    /// Wire protocol version. This must be [`PROTOCOL_V1`].
    pub version: u16,
    /// Identifier copied from the corresponding request.
    pub request_id: RequestId,
    /// Successful data or an actionable API error.
    #[serde(flatten)]
    pub payload: ResponsePayload<T>,
}

impl<T> ResponseEnvelope<T> {
    /// Creates a successful protocol version 1 response.
    #[must_use]
    pub const fn success(request_id: RequestId, data: T) -> Self {
        Self {
            kind: EnvelopeKind::Response,
            version: PROTOCOL_V1,
            request_id,
            payload: ResponsePayload::Success { data },
        }
    }

    /// Creates a failed protocol version 1 response.
    #[must_use]
    pub const fn failure(request_id: RequestId, error: ApiError) -> Self {
        Self {
            kind: EnvelopeKind::Response,
            version: PROTOCOL_V1,
            request_id,
            payload: ResponsePayload::Error { error },
        }
    }

    /// Returns whether this envelope uses the supported protocol version.
    #[must_use]
    pub const fn is_supported(&self) -> bool {
        self.version == PROTOCOL_V1 && matches!(self.kind, EnvelopeKind::Response)
    }
}

/// Mutually exclusive success and failure response bodies.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum ResponsePayload<T> {
    /// A successful response.
    Success {
        /// Request-specific response data.
        data: T,
    },
    /// A failed response.
    Error {
        /// Actionable error information.
        error: ApiError,
    },
}

/// Versioned event emitted asynchronously by the daemon.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EventEnvelope<T> {
    /// Stable envelope discriminator. Constructors always set this to `event`.
    pub kind: EnvelopeKind,
    /// Wire protocol version. This must be [`PROTOCOL_V1`].
    pub version: u16,
    /// Stable dotted event name, such as `session.status_changed`.
    pub event: String,
    /// Monotonic sequence within the emitting daemon lifetime.
    pub sequence: u64,
    /// Event-specific body.
    pub payload: T,
}

impl<T> EventEnvelope<T> {
    /// Wraps a named event body and sequence using protocol version 1.
    #[must_use]
    pub fn v1(event: impl Into<String>, sequence: u64, payload: T) -> Self {
        Self {
            kind: EnvelopeKind::Event,
            version: PROTOCOL_V1,
            event: event.into(),
            sequence,
            payload,
        }
    }

    /// Returns whether this envelope uses the supported protocol version.
    #[must_use]
    pub const fn is_supported(&self) -> bool {
        self.version == PROTOCOL_V1 && matches!(self.kind, EnvelopeKind::Event)
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn request_v1_round_trips_and_carries_version() {
        let request = RequestEnvelope::v1("session.create", json!({ "projectId": "project-1" }));
        let value = serde_json::to_value(&request).expect("request should serialize");
        let decoded: RequestEnvelope<serde_json::Value> =
            serde_json::from_value(value.clone()).expect("request should deserialize");

        assert_eq!(decoded, request);
        assert!(decoded.is_supported());
        assert_eq!(decoded.version, PROTOCOL_V1);
        assert_eq!(decoded.kind, EnvelopeKind::Request);
        assert_eq!(
            value,
            json!({
                "kind": "request",
                "version": 1,
                "requestId": request.request_id,
                "method": "session.create",
                "payload": { "projectId": "project-1" }
            })
        );
    }

    #[test]
    fn failure_response_round_trips_with_actionable_error() {
        let request_id = RequestId::new();
        let response: ResponseEnvelope<()> = ResponseEnvelope::failure(
            request_id,
            ApiError::new("executable_not_found", "Could not start Codex")
                .with_action("Install Codex or configure a custom executable")
                .with_detail("executable", "codex"),
        );
        let json = serde_json::to_string(&response).expect("response should serialize");
        let decoded: ResponseEnvelope<()> =
            serde_json::from_str(&json).expect("response should deserialize");

        assert_eq!(decoded, response);
        assert_eq!(decoded.kind, EnvelopeKind::Response);

        let value = serde_json::to_value(&decoded).expect("response should serialize to a value");
        assert_eq!(
            value,
            json!({
                "kind": "response",
                "version": 1,
                "requestId": request_id,
                "status": "error",
                "error": {
                    "code": "executable_not_found",
                    "message": "Could not start Codex",
                    "action": "Install Codex or configure a custom executable",
                    "details": { "executable": "codex" }
                }
            })
        );
    }

    #[test]
    fn event_v1_round_trips() {
        let event = EventEnvelope::v1("session.updated", 42, json!({ "sessionId": "session-1" }));
        let value = serde_json::to_value(&event).expect("event should serialize");
        let decoded: EventEnvelope<serde_json::Value> =
            serde_json::from_value(value.clone()).expect("event should deserialize");

        assert_eq!(decoded, event);
        assert!(decoded.is_supported());
        assert_eq!(decoded.kind, EnvelopeKind::Event);
        assert_eq!(
            value,
            json!({
                "kind": "event",
                "version": 1,
                "event": "session.updated",
                "sequence": 42,
                "payload": { "sessionId": "session-1" }
            })
        );
    }

    #[test]
    fn unsupported_version_is_detected() {
        let request = RequestEnvelope {
            kind: EnvelopeKind::Request,
            version: PROTOCOL_V1 + 1,
            request_id: RequestId::new(),
            method: "system.hello".to_owned(),
            payload: (),
        };

        assert!(!request.is_supported());
    }

    #[test]
    fn mismatched_envelope_kind_is_rejected() {
        let request = RequestEnvelope {
            kind: EnvelopeKind::Event,
            version: PROTOCOL_V1,
            request_id: RequestId::new(),
            method: "system.hello".to_owned(),
            payload: (),
        };

        assert!(!request.is_supported());
    }

    #[test]
    fn catalog_application_version_matches_cargo_package() {
        let catalog: serde_json::Value =
            serde_json::from_str(include_str!("../../../protocol/catalog.json"))
                .expect("protocol catalog should parse");

        assert_eq!(catalog["protocolVersion"], PROTOCOL_V1);
        assert_eq!(catalog["applicationVersion"], APPLICATION_VERSION);
        assert_eq!(APPLICATION_VERSION, env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn request_envelope_rejects_unknown_top_level_fields() {
        let request = RequestEnvelope::v1("system.hello", json!({}));
        let mut value = serde_json::to_value(request).expect("request should serialize");
        assert!(
            serde_json::from_value::<RequestEnvelope<serde_json::Value>>(value.clone()).is_ok()
        );
        value["unexpected"] = json!(true);
        assert!(serde_json::from_value::<RequestEnvelope<serde_json::Value>>(value).is_err());
    }
}
